[tool.poetry]
name = "pocket-api"
version = "0.1.0"
description = ""
authors = ["kenji imai <imakenfever@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.0"
pocket = "^0.3.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
